name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2  # This step checks out your repository

      - name: Use Node.js ${{ matrix.node-version }}  # This is the name of the next step
        uses: actions/setup-node@v1  # This is the action for setting up Node.js
        with:
          node-version: ${{ matrix.node-version }}  # This specifies the Node.js version to use

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test

